aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "package.json" }}

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}

version: 2
jobs:
  test-node-6:
    working_directory: ~/test-karma-rollup-tape-6
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: |
        node --version
        npm --version
        npm install
      - save-cache: *save-cache
      - run: |
        npm test
  test-node-8:
    working_directory: ~/test-karma-rollup-tape-8
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: |
        node --version
        npm --version
        npm install
      - save-cache: *save-cache
      - run: |
        npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-8
      - test-node-6
