version: 2.0

jobs:
  "node-10":
    docker:
      - image: circleci/node:10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/test-karma-rollup-tape
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run:
          name: Run tests
          command: npm test

  "node-12":
    docker:
      - image: circleci/node:12-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/test-karma-rollup-tape
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - "node-10"
      - "node-12"
