version: 2.0

jobs:
  "node-6":
    docker:
      - image: circleci/node:6
    working_directory: ~/test-karma-rollup-tape
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run:
          name: Run tests
          command: npm test

  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/test-karma-rollup-tape
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - "node-6"
      - "node-8"
